version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - run: echo "Build app"
  test:
    docker:
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: Eslint
          command: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test